//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.logiscompanyinfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblCompanyID;
	protected global::System.Web.UI.WebControls.Label lblCompanyName;
	protected global::System.Web.UI.WebControls.Label lblCompanyUnifiedCode;
	protected global::System.Web.UI.WebControls.Label lblToPublicAccount;
	protected global::System.Web.UI.WebControls.Label lblToPrivateAccount;
	protected global::System.Web.UI.WebControls.Label lblCompanyLocation;
	protected global::System.Web.UI.WebControls.Label lblCompanyAddress;
	protected global::System.Web.UI.WebControls.Label lblBusinessNature;
	protected global::System.Web.UI.WebControls.Label lblLegalRepresentative;
	protected global::System.Web.UI.WebControls.Label lblTelephone;
	protected global::System.Web.UI.WebControls.Label lblMobile;
	protected global::System.Web.UI.WebControls.Label lblFaxNo;


       
    }
}
