//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.exceptioninfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtDeliverId;
		protected global::System.Web.UI.WebControls.TextBox txtExceptionType;
		protected global::System.Web.UI.WebControls.TextBox txtExceptiondescribe;
		protected global::System.Web.UI.WebControls.TextBox txtExceptionDispose;
		protected global::System.Web.UI.WebControls.TextBox txtSender;
		protected global::System.Web.UI.WebControls.TextBox txtSendTime;
		protected global::System.Web.UI.WebControls.TextBox txtConductor;
		protected global::System.Web.UI.WebControls.TextBox txtDisposeTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
