//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.vehicledelivery {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtDeliveryId;
		protected global::System.Web.UI.WebControls.TextBox txtDeviceId;
		protected global::System.Web.UI.WebControls.TextBox txtVehicleId;
		protected global::System.Web.UI.WebControls.TextBox txtDriver1Id;
		protected global::System.Web.UI.WebControls.TextBox txtDriver2Id;
		protected global::System.Web.UI.WebControls.TextBox txtOrigin;
		protected global::System.Web.UI.WebControls.TextBox txtBeginTime;
		protected global::System.Web.UI.WebControls.TextBox txtMinTempThreshold;
		protected global::System.Web.UI.WebControls.TextBox txtMaxTempThreshold;
		protected global::System.Web.UI.WebControls.TextBox txtMinHumThreshold;
		protected global::System.Web.UI.WebControls.TextBox txtMaxHumThreshold;
		protected global::System.Web.UI.WebControls.TextBox txtIfEnd;
		protected global::System.Web.UI.WebControls.TextBox txtRecordId;
		protected global::System.Web.UI.WebControls.TextBox txtAuditor;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
