//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.vehicledelivery {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblDeliveryId;
	protected global::System.Web.UI.WebControls.Label lblDeviceId;
	protected global::System.Web.UI.WebControls.Label lblVehicleId;
	protected global::System.Web.UI.WebControls.Label lblDriver1Id;
	protected global::System.Web.UI.WebControls.Label lblDriver2Id;
	protected global::System.Web.UI.WebControls.Label lblOrigin;
	protected global::System.Web.UI.WebControls.Label lblBeginTime;
	protected global::System.Web.UI.WebControls.Label lblMinTempThreshold;
	protected global::System.Web.UI.WebControls.Label lblMaxTempThreshold;
	protected global::System.Web.UI.WebControls.Label lblMinHumThreshold;
	protected global::System.Web.UI.WebControls.Label lblMaxHumThreshold;
	protected global::System.Web.UI.WebControls.Label lblIfEnd;
	protected global::System.Web.UI.WebControls.Label lblRecordId;
	protected global::System.Web.UI.WebControls.Label lblAuditor;


       
    }
}
