//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.productinfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtProductId;
		protected global::System.Web.UI.WebControls.TextBox txtProductName;
		protected global::System.Web.UI.WebControls.TextBox txtProductType;
		protected global::System.Web.UI.WebControls.TextBox txtSpecification;
		protected global::System.Web.UI.WebControls.TextBox txtManufaturer;
		protected global::System.Web.UI.WebControls.TextBox txtBatchNum;
		protected global::System.Web.UI.WebControls.TextBox txtDataofManufaturer;
		protected global::System.Web.UI.WebControls.TextBox txtUnitofMeasurement;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
