//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.productinfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblProductId;
	protected global::System.Web.UI.WebControls.Label lblProductName;
	protected global::System.Web.UI.WebControls.Label lblProductType;
	protected global::System.Web.UI.WebControls.Label lblSpecification;
	protected global::System.Web.UI.WebControls.Label lblManufaturer;
	protected global::System.Web.UI.WebControls.Label lblBatchNum;
	protected global::System.Web.UI.WebControls.Label lblDataofManufaturer;
	protected global::System.Web.UI.WebControls.Label lblUnitofMeasurement;


       
    }
}
