//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.productdelivery {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtDeliveryId;
		protected global::System.Web.UI.WebControls.TextBox txtProductId;
		protected global::System.Web.UI.WebControls.TextBox txtQuantity;
		protected global::System.Web.UI.WebControls.TextBox txtOrigin;
		protected global::System.Web.UI.WebControls.TextBox txtBeginTime;
		protected global::System.Web.UI.WebControls.TextBox txtDestination;
		protected global::System.Web.UI.WebControls.TextBox txtLongitude;
		protected global::System.Web.UI.WebControls.TextBox txtLatitude;
		protected global::System.Web.UI.WebControls.TextBox txtPredictDeliveryTime;
		protected global::System.Web.UI.WebControls.TextBox txtDeliveryTime;
		protected global::System.Web.UI.WebControls.TextBox txtClientId;
		protected global::System.Web.UI.WebControls.TextBox txtArriveTime;
		protected global::System.Web.UI.WebControls.TextBox txtSigner;
		protected global::System.Web.UI.WebControls.TextBox txtTelephone;
		protected global::System.Web.UI.WebControls.CheckBox chkIsBackFee;
		protected global::System.Web.UI.WebControls.TextBox txtAmount;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDeliver;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
