//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.productdelivery {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblDeliveryId;
	protected global::System.Web.UI.WebControls.Label lblProductId;
	protected global::System.Web.UI.WebControls.Label lblQuantity;
	protected global::System.Web.UI.WebControls.Label lblOrigin;
	protected global::System.Web.UI.WebControls.Label lblBeginTime;
	protected global::System.Web.UI.WebControls.Label lblDestination;
	protected global::System.Web.UI.WebControls.Label lblLongitude;
	protected global::System.Web.UI.WebControls.Label lblLatitude;
	protected global::System.Web.UI.WebControls.Label lblPredictDeliveryTime;
	protected global::System.Web.UI.WebControls.Label lblDeliveryTime;
	protected global::System.Web.UI.WebControls.Label lblClientId;
	protected global::System.Web.UI.WebControls.Label lblArriveTime;
	protected global::System.Web.UI.WebControls.Label lblSigner;
	protected global::System.Web.UI.WebControls.Label lblTelephone;
	protected global::System.Web.UI.WebControls.Label lblIsBackFee;
	protected global::System.Web.UI.WebControls.Label lblAmount;
	protected global::System.Web.UI.WebControls.Label lblIsDeliver;


       
    }
}
