//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.vehicleinfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtVehicleId;
		protected global::System.Web.UI.WebControls.TextBox txtVehicleName;
		protected global::System.Web.UI.WebControls.TextBox txtVehicleNumber;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyId;
		protected global::System.Web.UI.WebControls.TextBox txtVehicleType;
		protected global::System.Web.UI.WebControls.TextBox txtLoadCapacity;
		protected global::System.Web.UI.WebControls.TextBox txtLicensePhoto;
		protected global::System.Web.UI.WebControls.TextBox txtVehiclePhoto;
		protected global::System.Web.UI.WebControls.TextBox txtIFBelongsto;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
