//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.driverinfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblDriverId;
	protected global::System.Web.UI.WebControls.Label lblDriverName;
	protected global::System.Web.UI.WebControls.Label lblDriverSex;
	protected global::System.Web.UI.WebControls.Label lblFamilyAddress;
	protected global::System.Web.UI.WebControls.Label lblMobile;
	protected global::System.Web.UI.WebControls.Label lblIdNumber;
	protected global::System.Web.UI.WebControls.Label lblDriverLicense;
	protected global::System.Web.UI.WebControls.Label lblLicenseType;
	protected global::System.Web.UI.WebControls.Label lblDriverLocation;
	protected global::System.Web.UI.WebControls.Label lblEmergencyContact;
	protected global::System.Web.UI.WebControls.Label lblEmergencyMobile;
	protected global::System.Web.UI.WebControls.Label lblEmergencyRelations;
	protected global::System.Web.UI.WebControls.Label lblDriverPhoto;
	protected global::System.Web.UI.WebControls.Label lblCompanyId;
	protected global::System.Web.UI.WebControls.Label lblType;


       
    }
}
