//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.deliverycurtempinfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtDeliveryId;
		protected global::System.Web.UI.WebControls.TextBox txtTemperature1;
		protected global::System.Web.UI.WebControls.TextBox txtHumidity1;
		protected global::System.Web.UI.WebControls.TextBox txtTemperature2;
		protected global::System.Web.UI.WebControls.TextBox txtHumidity2;
		protected global::System.Web.UI.WebControls.TextBox txtTemperature3;
		protected global::System.Web.UI.WebControls.TextBox txtHumidity3;
		protected global::System.Web.UI.WebControls.TextBox txtCurrentTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
