//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.usersinfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUserId;
		protected global::System.Web.UI.WebControls.TextBox txtUserName;
		protected global::System.Web.UI.WebControls.TextBox txtUserSex;
		protected global::System.Web.UI.WebControls.TextBox txtUserPassword;
		protected global::System.Web.UI.WebControls.TextBox txtUserState;
		protected global::System.Web.UI.WebControls.TextBox txtUserTypeId;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyId;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
