//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.deviceuseinfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblDeviceId;
	protected global::System.Web.UI.WebControls.Label lblVehicleId;
	protected global::System.Web.UI.WebControls.Label lblIfBind;
	protected global::System.Web.UI.WebControls.Label lblBindTime;
	protected global::System.Web.UI.WebControls.Label lblUnbindTime;
	protected global::System.Web.UI.WebControls.Label lblComment;


       
    }
}
