//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.refueling {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtVehicleID;
		protected global::System.Web.UI.WebControls.TextBox txtDeliveryId;
		protected global::System.Web.UI.WebControls.TextBox txtLongitude;
		protected global::System.Web.UI.WebControls.TextBox txtLatitude;
		protected global::System.Web.UI.WebControls.TextBox txtPetrolStation;
		protected global::System.Web.UI.WebControls.TextBox txtMoney;
		protected global::System.Web.UI.WebControls.TextBox txtQuantity;
		protected global::System.Web.UI.WebControls.TextBox txtRefuelTime;
		protected global::System.Web.UI.WebControls.TextBox txtInvoicePhoto;
		protected global::System.Web.UI.WebControls.TextBox txtIfVerifyed;
		protected global::System.Web.UI.WebControls.TextBox txtVerfielId;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
