//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.refueling {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblVehicleID;
	protected global::System.Web.UI.WebControls.Label lblDeliveryId;
	protected global::System.Web.UI.WebControls.Label lblLongitude;
	protected global::System.Web.UI.WebControls.Label lblLatitude;
	protected global::System.Web.UI.WebControls.Label lblPetrolStation;
	protected global::System.Web.UI.WebControls.Label lblMoney;
	protected global::System.Web.UI.WebControls.Label lblQuantity;
	protected global::System.Web.UI.WebControls.Label lblRefuelTime;
	protected global::System.Web.UI.WebControls.Label lblInvoicePhoto;
	protected global::System.Web.UI.WebControls.Label lblIfVerifyed;
	protected global::System.Web.UI.WebControls.Label lblVerfielId;


       
    }
}
