//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.vehicleupkeep {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtVehicleId;
		protected global::System.Web.UI.WebControls.TextBox txtKilometres;
		protected global::System.Web.UI.WebControls.TextBox txtUpkeepDescribe;
		protected global::System.Web.UI.WebControls.TextBox txtUpkeepMoneys;
		protected global::System.Web.UI.WebControls.TextBox txtUpkeepTime;
		protected global::System.Web.UI.WebControls.TextBox txtUpkeepMan;
		protected global::System.Web.UI.WebControls.TextBox txtUpkeepLocation;
		protected global::System.Web.UI.WebControls.TextBox txtInvoicePhoto;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
