//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYePlat.Web.vehicleupkeep {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblVehicleId;
	protected global::System.Web.UI.WebControls.Label lblKilometres;
	protected global::System.Web.UI.WebControls.Label lblUpkeepDescribe;
	protected global::System.Web.UI.WebControls.Label lblUpkeepMoneys;
	protected global::System.Web.UI.WebControls.Label lblUpkeepTime;
	protected global::System.Web.UI.WebControls.Label lblUpkeepMan;
	protected global::System.Web.UI.WebControls.Label lblUpkeepLocation;
	protected global::System.Web.UI.WebControls.Label lblInvoicePhoto;


       
    }
}
